### ISSUE TITLE
export component name error

### ISSUE THREAD

**Issue by chentianxin** [xbmlz/solid-color#1]
![image](https://user-images.githubusercontent.com/49486355/219530922-872693d3-cda3-4daf-a7eb-131dbe8e7258.png)
`SketchPikcer` rename to `SketchPicker`

**Comment by xbmlz** [comment]
> ![image](https://user-images.githubusercontent.com/49486355/219530922-872693d3-cda3-4daf-a7eb-131dbe8e7258.png) `SketchPikcer` rename to `SketchPicker`

Thank you for your feedback. It has been fixed in v0.0.4
